FROM node:22-alpine3.20 AS build
WORKDIR /app
COPY package.json package-lock.json ./
COPY tsconfig.base.json tsconfig.json ./
COPY apps/backend ./apps/backend
COPY packages/core ./packages/core
COPY ./ ./

RUN npm install
RUN npm run build
RUN npm run build:backend

ENV PORT=4000
ENV CLIENT_URL=http://localhost:3000

EXPOSE 4000
CMD ["node", "apps/backend/dist/index.mjs"]