services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.backend
    ports:
      - '4000:4000'
    environment:
      PORT: 4000
      CLIENT_URL: http://localhost:3000
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile.frontend
    ports:
      - '3000:80'
    environment:
      VITE_WEBSOCKET_SERVER_URL: http://localhost:4000
    depends_on:
      - backend
