services:
  backend:
  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./packages/core:/packages/core # Defining unpublished packages directory for build
